// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dknuxhoufzvldjissnyl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRrbnV4aG91Znp2bGRqaXNzbnlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5MzA0NTIsImV4cCI6MjA3NDUwNjQ1Mn0.8eHGARhP8airfASOTNH_9QGyucYNzFKZ3haSikJZEoo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});